### ISSUE TITLE
Installing and configuration of the rabbitmq_mqtt plugin

### ISSUE THREAD

**Issue by vielmetti** [saltstack-formulas/rabbitmq-formula#15]
Hi, I'm using rabbitmq-formula and am looking to install and configure the rabbitmq_mqtt plugin with it.

At some point I'll need a stanza like this

```
[
   {rabbit_mqtt, [
      {tcp_listeners,[{"10.8.0.1", 1833}]}
   ]}
].
```

in a config file, but I'm unclear on where to start to add that in.

**Comment by gravyboat** [comment]
The rabbitmq formula doesn't currently have a `files` directory, since most of the config is handled via plugins here: https://github.com/saltstack-formulas/rabbitmq-formula/blob/master/rabbitmq/config.sls. I'd suggest to expand the existing config sls via your own fork, or create a new file that manages the configuration files specifically.

**Comment by vielmetti** [comment]
Thanks @gravyboat I'll look through this and figure out something that works.

**Comment by gravyboat** [comment]
@vielmetti Sounds good, if you come up with something good, please make a PR so we can review it and get it merged back into the main formula!
